services:
  scheduler:
    volumes:
      - ./chroma_db:/usr/local/airflow/chroma_db
  dag-processor:
    volumes:
      - ./chroma_db:/usr/local/airflow/chroma_db
  triggerer:
    volumes:
      - ./chroma_db:/usr/local/airflow/chroma_db
