bedrock:
  region: ap-south-1
  # pricing unit: USD per 1,000 tokens
  llm:
    small:
      id: meta.llama3-8b-instruct-v1:0
      label: Llama-3-8B
      pricing:
        input: 0.0003
        output: 0.0006

    large:
      id: meta.llama3-70b-instruct-v1:0
      label: Llama-3-70B
      pricing:
        input: 0.00265
        output: 0.0035

    critic:
      id: mistral.mistral-7b-instruct-v0:2
      label: Mistral-7B
      max_tokens: 512
      pricing:
        input: 0.0002
        output: 0.0002

  embeddings:
    id: amazon.titan-embed-text-v2:0
    max_input: 8000
